version: '3.7'

networks:
  network:
    driver: ${NETWORKS_DRIVER?}

services:
  php-fpm:
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG?}
    volumes:
      - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
    networks:
      - network
    extra_hosts:
      - host.docker.internal:host-gateway

  nginx:
    volumes:
      - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
    ports:
      - "${NGINX_HOST_HTTP_PORT:-80}:80"
      - "${NGINX_HOST_HTTPS_PORT:-443}:443"
    networks:
      network:
        aliases:
          - ${APP_HOST?}
    depends_on:
      - php-fpm

  application:
    build:
      args:
        - APP_SSH_PASSWORD=${APP_SSH_PASSWORD?}
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG?}
    volumes:
      - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
    ports:
      - "${APPLICATION_SSH_HOST_PORT:-2222}:22"
    networks:
      - network
    extra_hosts:
      - host.docker.internal:host-gateway
