version: '3.7'

networks:
  network:
    driver: ${NETWORKS_DRIVER?}

volumes:
  postgres-data:
    name: postgres-data-${ENV?}
    driver: ${VOLUMES_DRIVER?}

services:
  php-fpm:
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG?}
    volumes:
      - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
    networks:
      - network
    extra_hosts:
      - host.docker.internal:host-gateway
    depends_on:
      - postgres
      - postgres-test

  nginx:
    volumes:
      - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
    ports:
      - "${NGINX_HOST_HTTP_PORT:-80}:80"
      - "${NGINX_HOST_HTTPS_PORT:-443}:443"
    networks:
      network:
        aliases:
          - ${APP_HOST?}
    depends_on:
      - php-fpm

  application:
    build:
      args:
        - APP_SSH_PASSWORD=${APP_SSH_PASSWORD?}
    environment:
      - PHP_IDE_CONFIG=${PHP_IDE_CONFIG?}
    volumes:
      - ${APP_CODE_PATH_HOST?}:${APP_CODE_PATH_CONTAINER?}
    ports:
      - "${APPLICATION_SSH_HOST_PORT:-2222}:22"
    networks:
      - network
    extra_hosts:
      - host.docker.internal:host-gateway

  postgres:
    image: postgres:${POSTGRES_VERSION?}
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-application_db}
      POSTGRES_USER: ${POSTGRES_USER:-application_user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD?}
    volumes:
      - postgres-data:/var/lib/postgresql/data:rw
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - network
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"

  postgres-test:
    image: postgres:${POSTGRES_VERSION?}
    environment:
      POSTGRES_DB: ${POSTGRES_DB_TEST:-application_db_test}
      POSTGRES_USER: ${POSTGRES_USER_TEST:-application_user_test}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD_TEST?}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d $${POSTGRES_DB_TEST} -U $${POSTGRES_USER_TEST}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - network
    ports:
      - "${POSTGRES_HOST_PORT_TEST:-5433}:5432"
